### ISSUE TITLE
Blacklist specific configuration options for sync

### ISSUE THREAD

**Issue by svenluijten** [Hackafe/atom-sync-settings#165]
Currently I'm using Atom across multiple PCs, but the environment paths differ, which makes synchronizing those specific settings useless. I'd love a blacklist on the package to let it know not to sync certain files and/or settings.

**Comment by dirk-thomas** [comment]
The package settings already allow you to enable / disable the sync of the following files:
* settings
* packages
* keymap
* styles
* init
* snippets

Can you provide some examples what files and/or setting you would like to blacklist?

**Comment by svenluijten** [comment]
The `atom-autocomplete-php` package requires the user to set paths to `composer.phar` and the `php` executable, but these paths aren't the same on all devices.

**Comment by rigor789** [comment]
For example `settings.json` could contain paths like these:
```json
...
"plantuml-preview": {
	"jarLocation": "C:\\bin\\PlantUML\\plantuml.jar",
	"dotLocation": "C:\\bin\\Graphviz\\bin\\dot.exe",
	"zoomToFit": false
}
...
```
In this case I would like to blacklist the `plantuml-preview.jarLocation` and `plantuml-preview.dotLocation` keys from my `settings.json`, while keeping the local value when restoring my settings from the gist.

I'd guess that would require an extra step when restoring, since we can't just override the local `settings.json` we have to go through the blacklisted keys, and merge their current values into the new `settings.json` from the backup (gist).
